/* 1. Opprette Recipe Type */
drop table COOKBOOK_RECIPE_TYPE;
create table COOKBOOK_RECIPE_TYPE(
    ID INT NOT NULL IDENTITY(1,1),
    RECIPE_TYPE_NAME VARCHAR(128),
    PRIMARY KEY (ID)
);

/* 2. Opprette Ingredient Category */
drop table COOKBOOK_INGREDIENT_CATEGORY;
create table COOKBOOK_INGREDIENT_CATEGORY(
    ID INT NOT NULL IDENTITY(1,1),
    INGREDIENT_CATEGORY_NAME VARCHAR(128)
    PRIMARY KEY(ID)
);

/* 3. Opprette Ingredient */
drop table COOKBOOK_INGREDIENT;
create table COOKBOOK_INGREDIENT(
    ID INT NOT NULL IDENTITY(1,1),
    INGREDIENT_NAME VARCHAR(256),
    INGREDIENT_CATEGORY_ID INT,
    PRIMARY KEY(ID),
    FOREIGN KEY (INGREDIENT_CATEGORY_ID) REFERENCES COOKBOOK_INGREDIENT_CATEGORY(ID)
);


/* 4. Opprette Recipe */
drop table COOKBOOK_RECIPE;
create table COOKBOOK_RECIPE(
    ID INT NOT NULL IDENTITY(1,1),
    RECIPE_NAME VARCHAR(256),
    RECIPE_DESCRIPTION VARCHAR(1024),
    RECIPE_TYPE_ID INT,
    DEFAULT_PORTIONS INT,
    PRIMARY KEY(ID),
    FOREIGN KEY (RECIPE_TYPE_ID) REFERENCES COOKBOOK_RECIPE_TYPE(ID)
);

/* 5. Opprette Recipe Steps  */
drop table COOKBOOK_RECIPE_STEP;
create table COOKBOOK_RECIPE_STEP(
    ID INT NOT NULL IDENTITY(1,1),
    STEP_DESCRIPTION VARCHAR(1024),
    STEP_ORDER INT,
    RECIPE_ID INT,
    PRIMARY KEY(ID),
    FOREIGN KEY (RECIPE_ID) REFERENCES COOKBOOK_RECIPE(ID)
);


/* 6. Opprette Recipe Ingredients */
drop table COOKBOOK_RECIPE_INGREDIENT;
create table COOKBOOK_RECIPE_INGREDIENT(
    ID INT NOT NULL IDENTITY(1,1),
    RECIPE_ID INT,
    INGREDIENT_ID INT,
    MEASUREMENT_TYPE_ID VARCHAR(16),
    MEASUREMENT_VALUE DECIMAL(19,2)
    FOREIGN KEY (RECIPE_ID) REFERENCES COOKBOOK_RECIPE(ID),
    FOREIGN KEY (INGREDIENT_ID) REFERENCES COOKBOOK_INGREDIENT(ID)
);

