INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('KARBONADEDEIG','KARBONADEDEIG',1)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('KJØTTDEIG','KJØTTDEIG',1)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('HVALKJØTT','HVALKJØTT',1)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('PØLSE','PØLSER',1)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('NAKKEKOTELETT','NAKKEKOTELETTER',1)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('LAKS','LAKS',2)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('TORSK','TORSK',2)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('SEI','SEI',2)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('BLÅSKJELL','BLÅSKJELL',3)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('HJERTESKJELL','HJERTESKJELL',3)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [[INGREDIENT_NAME_PLURAL], INGREDIENT_CATEGORY_ID]) values ('KYLLINGFILET','KYLLINGFILETER',4)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [[INGREDIENT_NAME_PLURAL], INGREDIENT_CATEGORY_ID]) values ('KYLLINGLÅR','KYLLINGLÅR',4)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('EGG','EGG',5)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('POTET','POTETER',6)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('TOMAT','TOMATER',6)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('MINITOMAT','MINITOMATER',6)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('AGURK','AGURKER',6)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('RUCCOLASALAT','RUCCOLASALAT',6)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [[INGREDIENT_NAME_PLURAL], INGREDIENT_CATEGORY_ID]) values ('HJERTESALAT','HJERESALAT',6)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('SPINAT','SPINAT',6)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('RØDLØK','RØDLØK',6)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('GUL LØK','GUL LØK',6)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('RØD PAPRIKA','RØD PAPRIKA',6)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('EPLE','EPLER',7)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('APPELSIN','APPELSINER',7)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('PÆRE','PÆRER',7)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('BLÅBÆR','BLÅBÆR',8)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('BRINGEBÆR','BRINGEBÆR',8)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('JORDBÆR','JORDBÆR',8)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('TYTTEBÆR','TYTTEBÆR',8)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('CASHEWNØTT','CASHEWNØTTER',9)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('PEANØTT','PEANØTTER',9)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('LINFRØ','LINFRØ',10)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('SESAMFRØ','SESAMFRØ',10)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('SOLSIKKEFRØ','SOLSIKKEFRØ',10)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('HVETEMEL','HVETEMEL',11)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('HAVREMEL','HAVREMEL',11)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('SPELTMEL','SPELTMEL',11)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('MELK','MELK',12)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('SMØR','SMØR',12)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('LETTRØMME','LETTRØMME',12)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('REVET OST','REVET OST',12)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('KESAM LETT','KESAM LETT',12)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('KESAM','KESAM',12)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('MATYOGHURT','MATYOGHURT',12)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('OREGANO','OREGANO',13)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('BASILIKUM','BASILIKUM',13)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('ROSMARIN','ROSMARIN',13)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('SALT','SALT',13)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('PEPPER','PEPPER',13)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('RASPOLJE','RASPOLJE',14)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('SOYASAUS','SOYASAUS',14)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('SUKKER','SUKKER',15)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('SUKRIN','SUKRIN',15)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('LYS SIRUP','LYS SIRUP',15)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('HONNING','HONNING',15)