INSERT INTO [dbo].[COOKBOOK_RECIPE_TYPE] 
    ([RECIPE_TYPE_NAME]) values ('FROKOST')

INSERT INTO [dbo].[COOKBOOK_RECIPE_TYPE] 
    ([RECIPE_TYPE_NAME]) values ('LUNSJ')

INSERT INTO [dbo].[COOKBOOK_RECIPE_TYPE] 
    ([RECIPE_TYPE_NAME]) values ('MIDDAG')

INSERT INTO [dbo].[COOKBOOK_RECIPE_TYPE] 
    ([RECIPE_TYPE_NAME]) values ('DESSERT')

INSERT INTO [dbo].[COOKBOOK_RECIPE_TYPE] 
    ([RECIPE_TYPE_NAME]) values ('FORRETT')

INSERT INTO [dbo].[COOKBOOK_RECIPE_TYPE] 
    ([RECIPE_TYPE_NAME]) values ('TILBEHØR')
    
INSERT INTO [dbo].[COOKBOOK_RECIPE_TYPE] 
    ([RECIPE_TYPE_NAME]) values ('DRIKKE')