INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('KARBONADEDEIG','KARBONADEDEIG',1)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('KJØTTDEIG','KJØTTDEIG',1)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('HVALKJØTT','HVALKJØTT',1)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('ROASTBIFF','ROASTBIFF',1)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('PARMASKINKE','PARMASKINKE',1)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('BACON','BACON',1)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('PØLSE','PØLSER',1)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('NAKKEKOTELETT','NAKKEKOTELETTER',1)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('LAKS','LAKS',2)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('SALMA LAKS','SALMA LAKS',2)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('TORSK','TORSK',2)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('SEI','SEI',2)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('BLÅSKJELL','BLÅSKJELL',3)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('HJERTESKJELL','HJERTESKJELL',3)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('SCAMPI','SCAMPI',3)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('REKER','REKER',3)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('KYLLINGFILET','KYLLINGFILETER',4)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('KYLLINGLÅR','KYLLINGLÅR',4)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('EGG','EGG',5)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('EGGEPLOMME','EGGEPLOMME',5)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('EGGEHVITT','EGGEHVITER',5)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('POTET','POTETER',6)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('PURRE','PURRER',6)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('MAIS','MAIS',6)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('HERMETISK HAKKETEDE TOMATER','HERMETISK HAKKETEDE TOMATER',6)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('TOMAT','TOMATER',6)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('MINITOMAT','MINITOMATER',6)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('SOLTØRKET TOMAT','SOLTØRKET TOMATER',6)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('AGURK','AGURKER',6)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('SQUASH','SQUASH',6)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('RUCCOLASALAT','RUCCOLASALAT',6)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('HJERTESALAT','HJERESALAT',6)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('KRISPSALAT','KRISPSALAT',6)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('SPINAT','SPINAT',6)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('BLOMKÅL','BLOMKÅLER',6)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('BROKKOLI','BROKKOLIER',6)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('ROSENKÅL','ROSENKÅL',6)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('SELLERIROT','SELLERIRØTTER',6)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('KÅLROT','KÅLRØTTER',6)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('AVOKADO','AVOKADOER',6)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('GULROT','GULRØTTER',6)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('RØDLØK','RØDLØK',6)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('GUL LØK','GUL LØK',6)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('VÅRLØK','VÅRLØK',6)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('ALFASPIRER','ALFASPIRER',6)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('BØNNESPIRER','BØNNESPIRER',6)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('SUKKERERTER','SUKKERERTER',6)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('INGEFÆR','INGEFÆR',6)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('RØD PAPRIKA','RØD PAPRIKA',6)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('TOMATPURÈ','TOMATPURÈ',6)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('RØD CHILI','RØD CHILI',6)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('GRØNN CHILI','GRØNN CHILI',6)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('SJAMPINJONG','SJAMPINJONGER',6)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('EPLE','EPLER',7)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('APPELSIN','APPELSINER',7)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('PÆRE','PÆRER',7)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('MANGO','MANGOER',7)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('PASJONSFRUKT','PASJONSFRUKTER',7)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('PASJONSFRUKT JUICE','PASJONSFRUKT JUICE',7)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('GRANATEPLE','GRANATEPLE',7)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('SITRON','SITRONER',7)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('LIME','LIME',7)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('KOKOSMELK','KOKOSMELK',7)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('BLÅBÆR','BLÅBÆR',8)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('BRINGEBÆR','BRINGEBÆR',8)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('JORDBÆR','JORDBÆR',8)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('TYTTEBÆR','TYTTEBÆR',8)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('CASHEWNØTT','CASHEWNØTTER',9)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('PEANØTT','PEANØTTER',9)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('PINJEKJERNER','PINJEKJERNER',9)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('LINFRØ','LINFRØ',10)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('SESAMFRØ','SESAMFRØ',10)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('SOLSIKKEFRØ','SOLSIKKEFRØ',10)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('COUSCOUS','COUSCOUS',11)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('RIS','RIS',11)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('RISNUDLER','RISNUDLER',11)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('HVETEMEL','HVETEMEL',11)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('HAVREMEL','HAVREMEL',11)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('SAMMALT GROVT MEL','SAMMALT GROVT MEL',11)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('HAVREGRYN','HAVREGRYN',11)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('SPELTMEL','SPELTMEL',11)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('MELK','MELK',12)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('LETTMELK','LETTMELK',12)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('HELMELK','HELMELK',12)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('KULTURMELK','KULTURMELK',12)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('SMØR','SMØR',12)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('LETTRØMME','LETTRØMME',12)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('MAJONES','MAJONES',12)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('REVET OST','REVET OST',12)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('MOZZARELLA OST','MOZZARELLA OST',12)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('PARMESANOST','PARMESANOST',12)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('FETAOST','FETAOST',12)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('PHILADELPHIAOST NATURELL','PHILADELPHIAOST NATURELL',12)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('KESAM LETT','KESAM LETT',12)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('KESAM','KESAM',12)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('MATYOGHURT','MATYOGHURT',12)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('YOGHURT NATURELL','YOGHURT NATURELL',12)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('MATFLØTE','MATFLØTE',12)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('KREMFLØTE','KREMFLØTE',12)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('CRÈME FRAÎCHE','CRÈME FRAÎCHE',12)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('OREGANO','OREGANO',13)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('BASILIKUM','BASILIKUM',13)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('FERSK BASILIKUM','FERSK BASILIKUM',13)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('TIMIAN','TIMIAN',13)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('ROSMARIN','ROSMARIN',13)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('SPISSKUMIN','SPISSKUMIN',13)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('SALT','SALT',13)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('HAVSALT','HAVSALT',13)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('PEPPER','PEPPER',13)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('HVITLØK','HVITLØK',13)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('KORIANDER','KORIANDER',13)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('LAURBLAD','LAURBLADER',13)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('PERSILLE','PERSILLE',13)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('GURKEMEIE','GURKEMEIE',13)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('GARAM MASALA','GARAM MASALA',13)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('CHILI PULVER','CHILI PULVER',13)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('KYLLINGBULJONG','KYLLINGBULJONGER',13)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('OKSEBULJONG','OKSEBULJONGER',13)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('GRØNNSAKBULJONG','GRØNNSAKBULJONGER',13)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('FISKEBULJONG','FISKEBULJONGER',13)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('KARDEMOMME','KARDEMOMME',13)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('GRILLKRYDDER','GRILLKRYDDER',13)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('RASPOLJE','RASPOLJE',14)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('RISEDDIK','RISEDDIK',14)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('EPLESIDEREDDIK','EPLESIDEREDDIK',14)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('EDDIK 7%','EDDIK 7%',14)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('PAD THAI SAUS','PAD THAI SAUS',14)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('SURSØTSAUS','SURSØTSAUS',14)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('SOYASAUS','SOYASAUS',14)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('OLIVENOLJE','OLIVENOLJE',14)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('KOKOSOLJE','KOKOSOLJE',14)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('KARRI PASTE','KARRI PASTE',14)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('SUKKER','SUKKER',15)

    INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('BRUNT SUKKER','BRUNT SUKKER',15)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('SUKRIN','SUKRIN',15)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('KOKKOSMASSE','KOKKOSMASSE',15)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('MELIS','MELIS',15)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('MELKESJOKOLADE','MELKESJOKOLADE',15)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('HVIT SJOKOLADE','HVIT SJOKOLADE',15)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('MØRK SJOKOLADE','MØRK SJOKOLADE',15)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('LYS SIRUP','LYS SIRUP',15)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('HONNING','HONNING',15)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('VANILJEESSENS','VANILJEESSENS',15)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('VANILJESTANG','VANILJESTENGER',15)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('BAKEKAKAO','BAKEKAKAO',15)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('PENNE PASTA','PENNE PASTA',16)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('SPAGETTI PASTA','SPAGETTI PASTA',16)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('LASAGNEPLATE','LASAGNEPLATER',16)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('DIGESTIVE KJEKS','DIGESTIVE KJEKS',17)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('OREOKJEKS','OREOKJEKS',17)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('VANN','VANN',18)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('TØRRGJÆR','TØRRGJØR',18)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('FERSK GJÆR','FERSK GJÆR',18)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('BAKEPULVER','BAKEPULVER',18)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('VANILJEPULVER','VANILJEPULVER',18)

INSERT INTO [dbo].[COOKBOOK_INGREDIENT] 
    ([INGREDIENT_NAME_SINGLE], [INGREDIENT_NAME_PLURAL], [INGREDIENT_CATEGORY_ID]) values ('GELATINPLATE','GELATINPLATER',18)
