INSERT INTO [dbo].[COOKBOOK_INGREDIENT_CATEGORY] 
    ([INGREDIENT_CATEGORY_NAME]) values ('KJØTT') /*ID: 1*/

INSERT INTO [dbo].[COOKBOOK_INGREDIENT_CATEGORY] 
    ([INGREDIENT_CATEGORY_NAME]) values ('FISK') /*ID: 2*/

INSERT INTO [dbo].[COOKBOOK_INGREDIENT_CATEGORY] 
    ([INGREDIENT_CATEGORY_NAME]) values ('SKALLDYR') /*ID: 3*/

INSERT INTO [dbo].[COOKBOOK_INGREDIENT_CATEGORY] 
    ([INGREDIENT_CATEGORY_NAME]) values ('FJØRFE') /*ID: 4*/

INSERT INTO [dbo].[COOKBOOK_INGREDIENT_CATEGORY] 
    ([INGREDIENT_CATEGORY_NAME]) values ('EGG') /*ID: 5*/

INSERT INTO [dbo].[COOKBOOK_INGREDIENT_CATEGORY] 
    ([INGREDIENT_CATEGORY_NAME]) values ('GRØNNSAK') /*ID: 6*/

INSERT INTO [dbo].[COOKBOOK_INGREDIENT_CATEGORY] 
    ([INGREDIENT_CATEGORY_NAME]) values ('FRUKT') /*ID: 7*/

INSERT INTO [dbo].[COOKBOOK_INGREDIENT_CATEGORY] 
    ([INGREDIENT_CATEGORY_NAME]) values ('BÆR') /*ID: 8*/

INSERT INTO [dbo].[COOKBOOK_INGREDIENT_CATEGORY] 
    ([INGREDIENT_CATEGORY_NAME]) values ('NØTTER') /*ID: 9*/

INSERT INTO [dbo].[COOKBOOK_INGREDIENT_CATEGORY] 
    ([INGREDIENT_CATEGORY_NAME]) values ('FRØ') /*ID: 10*/

INSERT INTO [dbo].[COOKBOOK_INGREDIENT_CATEGORY] 
    ([INGREDIENT_CATEGORY_NAME]) values ('KORN') /*ID: 11*/

INSERT INTO [dbo].[COOKBOOK_INGREDIENT_CATEGORY] 
    ([INGREDIENT_CATEGORY_NAME]) values ('MEIERI') /*ID: 12*/

INSERT INTO [dbo].[COOKBOOK_INGREDIENT_CATEGORY] 
    ([INGREDIENT_CATEGORY_NAME]) values ('KRYDDER/URT') /*ID: 13*/

INSERT INTO [dbo].[COOKBOOK_INGREDIENT_CATEGORY] 
    ([INGREDIENT_CATEGORY_NAME]) values ('OLJER/DRESSING/PASTE') /*ID: 14*/

INSERT INTO [dbo].[COOKBOOK_INGREDIENT_CATEGORY] 
    ([INGREDIENT_CATEGORY_NAME]) values ('SØTNING') /*ID: 15*/

INSERT INTO [dbo].[COOKBOOK_INGREDIENT_CATEGORY] 
    ([INGREDIENT_CATEGORY_NAME]) values ('ANNET') /*ID: 16*/