INSERT INTO [dbo].[COOKBOOK_RECIPE_INGREDIENT] 
    ([RECIPE_ID], [INGREDIENT_ID], [MEASUREMENT_TYPE_ID], [MEASUREMENT_VALUE]) values 
    (1, 149, 'gram', 400.0) /*DIGESTIVE KJEKS*/

INSERT INTO [dbo].[COOKBOOK_RECIPE_INGREDIENT] 
    ([RECIPE_ID], [INGREDIENT_ID], [MEASUREMENT_TYPE_ID], [MEASUREMENT_VALUE]) values 
    (1, 86, 'gram', 200.0) /*SMØR*/

INSERT INTO [dbo].[COOKBOOK_RECIPE_INGREDIENT] 
    ([RECIPE_ID], [INGREDIENT_ID], [MEASUREMENT_TYPE_ID], [MEASUREMENT_VALUE]) values 
    (1, 93, 'gram', 500.0) /*PHILADELPHIAOST NATURELL*/

INSERT INTO [dbo].[COOKBOOK_RECIPE_INGREDIENT] 
    ([RECIPE_ID], [INGREDIENT_ID], [MEASUREMENT_TYPE_ID], [MEASUREMENT_VALUE]) values 
    (1, 156, 'stk', 9.0) /*GELATINPLATE*/

INSERT INTO [dbo].[COOKBOOK_RECIPE_INGREDIENT] 
    ([RECIPE_ID], [INGREDIENT_ID], [MEASUREMENT_TYPE_ID], [MEASUREMENT_VALUE]) values 
    (1, 58, 'stk', 12.0) /*PASJONSFRUKT*/

INSERT INTO [dbo].[COOKBOOK_RECIPE_INGREDIENT] 
    ([RECIPE_ID], [INGREDIENT_ID], [MEASUREMENT_TYPE_ID], [MEASUREMENT_VALUE]) values 
    (1, 137, 'gram', 200.0) /*MELIS*/

INSERT INTO [dbo].[COOKBOOK_RECIPE_INGREDIENT] 
    ([RECIPE_ID], [INGREDIENT_ID], [MEASUREMENT_TYPE_ID], [MEASUREMENT_VALUE]) values 
    (1, 59, 'dl', 3.0) /*PASJONSFRUKT JUICE*/

INSERT INTO [dbo].[COOKBOOK_RECIPE_INGREDIENT] 
    ([RECIPE_ID], [INGREDIENT_ID], [MEASUREMENT_TYPE_ID], [MEASUREMENT_VALUE]) values 
    (1, 99, 'dl', 6.0) /*KREMFLØTE*/

INSERT INTO [dbo].[COOKBOOK_RECIPE_INGREDIENT] 
    ([RECIPE_ID], [INGREDIENT_ID], [MEASUREMENT_TYPE_ID], [MEASUREMENT_VALUE]) values 
    (1, 133, 'gram', 150.0) /*SUKKER*/